#logback 日志文件存储路径
log:
  path: /data/backend/log


#是否验证token开关
token:
  flag: true


#mybatis plus 设置/configuration配置测试和开发环境使用
mybatis-plus:
  #支持多个，多个以，割风如：classpath:mapper/*.xml,classpath:mapper/*.xml
  mapper-locations: classpath:mapper/*.xml
  configuration:
    call-setters-on-nulls: on
    #生产使用
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    #测试使用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
